version: "3"

services:

  webservice:
    build: webservice
    depends_on:
      - database
    ports:
      - 80:8088
    links:
      - database
    environment:
      MAIL_AUTH: "RqHDMR6WfMd9zMhr^kgDA4kZ0DJbEElu7Sb^B!#1uXVzDy%zW85yGIL#iI6D2%S*"
      DATABASE_URL: database:3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_DATABASE: cs53
      MAIL_SERVICE: mailservice:8085
      TIME_ZONE: "Europe/Oslo"
    restart: always

  mailservice:
    build: mailservice
    depends_on:
      - database
    ports:
      - 8085:8085
    links:
      - database
    environment:
      DATABASE_URL: database:3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_DATABASE: cs53
      MAIL_AUTH: "RqHDMR6WfMd9zMhr^kgDA4kZ0DJbEElu7Sb^B!#1uXVzDy%zW85yGIL#iI6D2%S*"
      USERNAME: csams.noreply@gmail.com
      PASSWORD: $mail_pwd
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - database

  database:
    build: dbservice
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: cs53
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dbservice/data:/var/lib/mysql