version: "3"

services:

  webservice:
    build: webservice
    depends_on:
      - database
    ports:
      - 80:8088
    links:
      - database
    environment:
      MAIL_AUTH: $MAILAUTH
      DATABASE_URL: database:3306
      DATABASE_USER: $DBUSER
      DATABASE_PASSWORD: $DBPW
      DATABASE_DATABASE: $DATABASEDB
      MAIL_SERVICE: mailservice:8085
      TIME_ZONE: "Europe/Oslo"
    restart: always

  mailservice:
    build: mailservice
    depends_on:
      - database
    ports:
      - 8085:8085
    links:
      - database
    environment:
      DATABASE_URL: database:3306
      DATABASE_USER: $DBUSER
      DATABASE_PASSWORD: $DBPW
      DATABASE_DATABASE: $DATABASEDB
      MAIL_AUTH: $MAILAUTH
      MAIL_PROVIDER: $MAILPROVIDER
      USERNAME: $MAILUSER
      PASSWORD: $MAILPW
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - database

  database:
    build: dbservice
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: $DATABASEDB
      MYSQL_ROOT_PASSWORD: $DBPW
    volumes:
      - ./dbservice/data:/var/lib/mysql